name: "Bug report"
description: Create an issue describing a bug.
title: "[BUG] - <title>"
labels: [
  "bug"
]
body:
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: Please enter an explicit description of your issue
      placeholder: Short and explicit description of your incident...
    validations:
      required: true
  - type: textarea
    id: reprod
    attributes:
      label: "Reproduction steps"
      description: Steps to reproduce the behavior
      value: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
      render: bash
    validations:
      required: true
  - type: textarea
    id: screenshot
    attributes:
      label: "Screenshots"
      description: If applicable, add screenshots to help explain your problem.
      value: |
        ![DESCRIPTION](LINK.png)
      render: bash
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: "Logs"
      description: Please copy and paste any relevant log output if available.
      render: bash
    validations:
      required: false
  - type: input
    id: android-version
    attributes:
      label: "Android Version"
      description: On which Android version is this happening?
      placeholder: ex. Android 11
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Agreement
      description: By creating this issue I made sure that ...
      options:
        - label: I am using the latest supported Snapchat version.
          required: true
        - label: I am using the latest Snapmod version.
          required: true
        - label: There is no issue already describing my problem.
          required: true
